### ISSUE TITLE
Reconciliation with Nx Docker release

### ISSUE THREAD

**Issue by ptr727** [thehomerepot/nxwitness#14]
Regarding: https://support.networkoptix.com/hc/en-us/articles/360037973573-How-to-run-Nx-Server-in-Docker

I am still running on a VM, but I really do want to move to a container, and I don't want to build it myself if I don't have to.

I'm wondering what your thoughts are and path forward is given that Nx has released docker build scripts, but they are not publishing any docker images?

**Comment by thetonyluce** [comment]
Just an FYI - Nx has an experimental Dockerfile. You can find it on [Bitbucket.](https://bitbucket.org/networkoptix/nx_open_integrations/src/default/docker/).  Support article outlining Nx Support for Docker is [here](https://support.networkoptix.com/hc/en-us/articles/360037973573-How-to-run-Nx-Server-in-Docker).

**Comment by thehomerepot** [comment]
When I worked with their support team, they did not have plans to release a finished docker container image, only the scripts to build your own.
Mine is somewhat hacked together, as their package wants/expects systemd, which I don't like to have inside my docker containers. Because of this, I have to pull apart their .deb and remove all references and dependencies for systemd. I personally don't think either are a perfect solution, but I've been running mine without issue.

**Comment by ptrsmntc** [comment]
I am not familiar with the container vs. systemd arguments, but I do like the LSIO based builds (TZ, PUID, GUID, small, etc.).

I was hoping they would publish to docker hub, but if not then maybe there is a middle ground where they could support docker, and you / others could publish on docker hub using their build scripts and installers. 

I understand your version works, but I'd like to run something that they will support when things go wrong.

**Comment by thehomerepot** [comment]
As of today, they don't guarantee support for Docker anyway.

**Comment by ptrsmntc** [comment]
Understood, maybe then just wait and see where they take it. 
Seems almost pointless that they do the work if they are not going to eventually support it. 
And if it was me, I wouldn't support scripts, but I would support a docker hub version where the unit if delivery is known.

**Comment by thehomerepot** [comment]
I'm not saying they won't help you, but think of it like a Beta. I don't have any plans to stop releasing mine unless my "hacks" to get it working the way I want become too cumbersome.
