### ISSUE TITLE
trial licensing

### ISSUE THREAD

**Issue by rjcds** [thehomerepot/nxwitness#21]
I'm trying out Nx Witness for the first time, and am hoping to get it running on Docker with your build- thank you !

I've tried two different versions (4.0.x and 4.1.x) but each time I try and activate a trial license it gives me 0000-0000-0000-0005, which expired in March 2020.

I presume it's somehow tied to the docker image ?

I can't contact support because it says the license key is invalid - so it won't let me submit the form !!

Any other ideas ?

**Comment by thehomerepot** [comment]
Did you already use 1 trial license? My only thought is the trial is likely tied to your HWID and will only generate 1 discrete trial license. Even in docker, your HWID will be the same and likely won't allow multiple trial licenses.
Having said that, I haven't tried trial licenses in docker as I have paid licenses for all of my cameras.

I'd follow these steps to create a support request post.
https://support.networkoptix.com/hc/en-us/articles/360042844374-How-to-submit-a-support-request

Be very clear that you're using my docker containers, but they may be able to provide some insight.
