### ISSUE TITLE
No local storage

### ISSUE THREAD

**Issue by griskevicius** [thehomerepot/nxwitness#27]
I've tried a lot of combinations. Latest one is a container with folowing volumes:
v /var/storage/vms/config:/config:rw -v /var/storage/vms/media:/media:rw -v /var/storage/vms/recordings:/recordings:rw -v /var/storage/vms/archive:/archive:rw -v /var/storage/vms/data:/opt/networkoptix/mediaserver/var:rw

Nx Witness does not complain with error message "No local storage", but still, there is no recordings. I am totally new to NX Witness and just started experimenting today. Trial license says I can record, using 1 time based license, NX Wintess says that I am recording, but nothing happens. Also I have a log where it says "Recording started (INFO QnRecordingManager(0x7f4aac08eae0): Recording started for camera uuid_75670747-a9e0-f80d-cf69-076a45e2a9e0) and so on. When I open local WebAdmin interface, o Monitoring, Storage tab there is no volume at all. I am not sure if this is a container or a Nx Witness problem. Maybe you have any tips?

**Comment by thehomerepot** [comment]
Can you run the following on your docker host
`docker exec -it nxwitness /bin/bash`
And this in the bash shell inside your docker container and share the full output
`df -Ph`

Browse here, and go to "Storage Locations". What's displayed?
http://ipaddress:7001/static/index.html#/health

Browse here and go to "Storage". What's displayed?
http://ipaddress:7001/static/index.html#/info

**Comment by griskevicius** [comment]
Thanks. I've already found a solution:
https://hub.docker.com/r/ptr727/nxwitness
This cool guy says that ZFS is not supported by default, and my server uses ZFS as a backend storage for docker and other volumes. So like he said:
Access the advanced settings page at http://hostname:7001/static/index.html#/advanced and set additionalLocalFsTypes to include the filesystem type.
Add fuse.grpcfuse for Docker for Windows, fuse.shfs for Unraid, and zfs for ZFS, e.g. fuse.grpcfuse,fuse.shfs,zfs.

Keep up the good work! Thanks!

**Comment by thehomerepot** [comment]
Interesting, it's worth noting that my storage is backed by ZFS and I do not have additionalLocalFsTypes set. Glad you got it working.
