### ISSUE TITLE
Storage configuration

### ISSUE THREAD

**Issue by xmclej** [thehomerepot/nxwitness#32]
Hi,  putting this here as could not find any other place to put it.

Context: Running OMV 5 (5.6.4-1) with portainer/docker (5:20.10.6~3-0~debian-buster)
Have 4 HDD's as a pool of storage (~11TB) with shared folders within (e.g. /archive)
Have 1 SSD for OS and storage for docker apps config folders (e.g. /config)

When I use the nxwitness docker image exactly as stated only the /config storage location shows up within nxwitness. Thats my problem. I have the following 2 volume mappings

Mounts
0
    Destination: /archive
    Mode:
    Propagation: rprivate
    RW: true
    Source: /srv/a0d1a4bd-3a11-40fd-beb5-a50188789a30/Storage/CCTV
    Type: bind
1
      Destination /config
      Mode
      Propagation rprivate
      RW true
      Source /srv/dev-disk-by-label-AppData/AppData/nxwitness
      Type bind

Is there a workaround for this issue?

**Comment by thehomerepot** [comment]
How large is the volume /config is mapped to? What FS types are the 2 source volumes?

**Comment by xmclej** [comment]
Hi,
/config is only a 250GB SSD so only about 200GB useable

All the disks are ext4, the pool puts 4 of them together using fuse.mergerfs and then shared folders are on top of this pool.

Filesystems
[cid:94fac10d-f1ac-416d-9dce-4f0afed6bc71]

Union filesystem
[cid:5ee357f7-c97a-49e2-b878-6b3b78350e8d]

Shared Folders
[cid:6574be50-857e-4e13-900f-fe7689d2e658]

Services - SMB/CIFS
[cid:6c229b8c-8be2-4cb4-94a2-4c6554f4e4e0]
Permissions for /config
[cid:9e06128c-4176-40e1-9167-99cc6a020eea]

Permissions for /archive
[cid:f4dd617b-4235-42e1-a6e0-415f822394d7]

Appreciate the response.

Best Regards,
Jason
________________________________

**Comment by thehomerepot** [comment]
Within the running container, run the following
`cat /proc/mounts`

Look for the /archive path and see what fstype it is. NX filters some fstypes unless you explicitly add them. The fstype for yours is probably 'fuse.shfs'. Once you determine that, load the following URL and look for the additionalLocalFsTypes field.
http://<nx_witness_ip>:7001/static/index.html#/advanced

Add your fstype for that value, save, and restart your container.

**Comment by xmclej** [comment]
Perfect, thanks that works. 
One last thing related to storage locations, the NXWitness client app, says.."Analytics data can take up large amounts of space. We recommend to choose another location for it instead of the system partition"

I tried adding another volume to the Docker similar to the /Archive path but in a different folder
/archive  /srv/a0d1a4bd-3a11-40fd-beb5-a50188789a30/Storage/CCTV  fstype: fuse.mergerfs
/analytics /srv/a0d1a4bd-3a11-40fd-beb5-a50188789a30/Storage/CCTV/Analytics  fstype: fuse.mergerfs 

But this one did not show up like the /archive one did....

**Comment by thehomerepot** [comment]
I'd just use your /archive path which is not your system partition.
