### ISSUE TITLE
/archive volume not showing up as storage device

### ISSUE THREAD

**Issue by shayne** [thehomerepot/nxwitness#4]
When following the readme the container starts and everything works fine except that the storage device /archive is not listed, and external NAS connections do not work.

If I manually mount a CIFS share to /mnt/<something> it shows up in the management UI.

**Comment by thehomerepot** [comment]
Can you share "docker inspect <container>" output?

**Comment by thehomerepot** [comment]
Could not validate the issue. No further details were given. Closing.
