### ISSUE TITLE
DW Spectrum build targets

### ISSUE THREAD

**Issue by ptr727** [thehomerepot/nxwitness#6]
Since I live in the US, I have to buy the DW Spectrum branded version, and use a DW Spectrum license.

Would you please consider creating a DW Spectrum target?
https://digital-watchdog.com/productdetail/DW-Spectrum-IPVMS/

**Comment by thehomerepot** [comment]
Already have one. I'm in the US as well, this is what is use.
https://github.com/thehomerepot/dwspectrum

**Comment by ptr727** [comment]
Great, thanks.
- Do you know if it is possible to move the license from an Ubuntu Server VM to the docker config directory, or do I need to contact support and re-license?
- I understand the license is currently tied to the MAC address (I read on the forum an official docker version is in the works), is the license maintained when the container is regenerated and a new dynamic MAC assigned? (I run bridged in Unraid and use the auto update plugin to keep containers updated)

**Comment by thehomerepot** [comment]
The license is more than just the Mac address. It's a hardware I'd that is generated by a handful of things. I currently run a docker container with it and my hwid does not change. You will have to migrate your license at least once. The other option if you don't want to deal with migrating licenses everytime you deploy the server to different  hardware is to tie your licenses to a raspberry pi running dw and use it just for licenses.
