### ISSUE TITLE
Empty continuation line in RUN command

### ISSUE THREAD

**Issue by mykter** [thehomerepot/nxwitness#9]
When building:
```
[WARNING]: Empty continuation line found in:
    RUN  apt-get update &&  apt-get install -y ...
[WARNING]: Empty continuation lines will become errors in a future release.
```
Not sure whether to fix by removing the 'sections', or splitting into multiple RUN commands.

**Comment by thehomerepot** [comment]
Test the following branch.
[Issue_9-Empty_Continuation_Line_In_Run_Command](https://github.com/thehomerepot/nxwitness/tree/Issue_9-Empty_Continuation_Line_In_Run_Command)

**Comment by thehomerepot** [comment]
Resolved.
